### ISSUE TITLE
FATAL: Errno::ETXTBSY: ruby_block[Copy MongoDB executables] (hipsnip-mongodb::default line 85) had an error: Errno::ETXTBSY: Text file busy - /usr/bin/mongod

### ISSUE THREAD

**Issue by cggaurav** [hipsnip-cookbooks/mongodb#5]
For the default installation

**Comment by motns** [comment]
Hi there,

Could you please provide a bit more info, so I can look into this further:
- What version of Chef client are you using?
- What OS and what environment (like Ubuntu 12.04 on Vagrant, etc.)?
- Just to double-check, you are getting this on the first run of Chef, on a fresh machine instance?

I haven't come across this one personally, but I wouldn't be surprised if this was something that was introduced by a recent update to Chef...

Thanks,
Adam

**Comment by cggaurav** [comment]
Chef '11.4' using Vagrant Omnibus
Ubuntu 12.06/64 bit.
I am getting this on provisions on Vagrant, not reloads, so not of high importance ATM.

**Comment by motns** [comment]
So if I understood correctly, you're getting this on sub-sequent Chef runs, but only on `vagrant provision`, not `vagrant reload`? Either way it sounds very peculiar... I'll see if I can reproduce it in my test environment, but I'm quite busy today, so I probably won't get to it until some time tomorrow.

**Comment by motns** [comment]
I've tried to reproduce this in the Test Kitchen integration test environment (VirtualBox 4.3.2, Vagrant 1.3.5, Ubuntu 12.04/64bit, Chef 11.10) in various setup scenarios and multiple runs, but couldn't get it to break. Since I've made some changes recently, could you please pull master and try again?

Either way I'm fairly certain this is not something we're doing in this cookbook, and is instead a bug (or transient error) either in the underlying Chef providers, or some elusive issue in Vagrant itself...

**Comment by motns** [comment]
I've just released version `1.2.0` with a number of fixes, and the integration test suites were all passing, so I'm hoping this issue has been resolved. Take the new release for a spin, and feel free to re-open this issue if you're still having problems!
