### ISSUE TITLE
Enabling Auth results in MongoDB Status check to fail

### ISSUE THREAD

**Issue by cggaurav** [hipsnip-cookbooks/mongodb#6]
```
FATAL: Mongo::OperationFailure: hipsnip-mongodb_check_node[127.0.0.1] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/hipsnip-mongodb/providers/mongod.rb line 83) had an error: Mongo::OperationFailure: Database command 'serverStatus' failed: (ok: '0.0'; errmsg: 'unauthorized').
```

**Comment by motns** [comment]
Well spotted! I think authentication support is a bit limited in our cookbook at the moment, partly because of the added complexity of using it in a clustered environment (private keys, etc.). Are you running this in a replica set, or just a single instance? I can probably fix the health check itself quite easily, but getting the replica set authentication up and running will take time.

**Comment by cggaurav** [comment]
I am running a single instance, for which we need to create admin users via the localhost exception. I have a PR for this. For replica sets, the current flow will do.

**Comment by motns** [comment]
I see. The health check would probably need to take whatever credentials you set up as an argument (or read it from the node attributes) - perhaps if you're already working on authentication support, you could make that change as well?

**Comment by motns** [comment]
Authentication support for both single nodes and replica sets has been implemented in master - this includes support for authenticated health checks, so this should be sorted.

**Comment by cggaurav** [comment]
+1
